### ISSUE TITLE
Epipolar error for fisheye camera

### ISSUE THREAD

**Issue by lsy125** [johannes-graeter/momo#2]
Hi All,

I come across this project when trying to find reference in computing epipolar error for fisheye camera. I have read the paper and skim through the code found in momo, but cannot find code for the epipolar error for fisheye camera. Maybe I have missed it, could anyone shows me where the code is? 
Thanks.

Regards,
Lee

**Comment by johannes-graeter** [comment]
Thanks for the interest in the project. The cost functions are defined here https://github.com/johannes-graeter/momo/blob/master/include/momo/cost_functions.hpp you need to construct the essential matrix first which is done in essential_matrix_builder.hpp . Note that the epipolar error is defined in3d i.e. the cosine of the angle between the line of sight and the epipolar plane in 3d and is quite easy to implement yourself.
